"use client"

import { motion } from "framer-motion"
import { Card, CardContent } from "@/components/ui/card"
import { 
  BookOpen, 
  Calendar, 
  Brain, 
  TrendingUp, 
  Download,
  Zap
} from "lucide-react"

const features = [
  {
    icon: Brain,
    title: "AI-Powered Study Guides",
    description: "Get personalized study materials generated by advanced AI based on your syllabus and learning style."
  },
  {
    icon: Calendar,
    title: "Smart Study Planner",
    description: "Automatically create optimized study schedules that adapt to your exam dates and available time."
  },
  {
    icon: Zap,
    title: "Interactive Flashcards",
    description: "Master concepts with AI-generated flashcards and spaced repetition algorithms."
  },
  {
    icon: BookOpen,
    title: "Practice Quizzes",
    description: "Test your knowledge with adaptive quizzes that focus on your weak areas."
  },
  {
    icon: TrendingUp,
    title: "Progress Tracking",
    description: "Monitor your learning progress with detailed analytics and performance insights."
  },
  {
    icon: Download,
    title: "Export Anywhere",
    description: "Download your study materials as PDF, Anki cards, or share with study groups."
  }
]

export function Features() {
  return (
    <section className="py-20 px-4">
      <div className="container mx-auto max-w-6xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl md:text-5xl font-bold mb-4">
            Everything You Need to <span className="text-primary">Succeed</span>
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Powerful features designed to make studying more effective and efficient
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              viewport={{ once: true }}
              whileHover={{ y: -5 }}
            >
              <Card className="h-full border-2 hover:border-primary/50 transition-colors">
                <CardContent className="p-6">
                  <div className="flex items-center gap-4 mb-4">
                    <div className="p-3 bg-primary/10 rounded-lg">
                      <feature.icon className="h-6 w-6 text-primary" />
                    </div>
                    <h3 className="text-xl font-semibold">{feature.title}</h3>
                  </div>
                  <p className="text-muted-foreground">{feature.description}</p>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}
